/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { Greeter, GreeterInterface } from "../Greeter";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";

const _abi = [
  {
    inputs: [],
    name: "_getRandomNumberZeroOrOne",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "playDopeRaiders",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "player1",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "player2",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102d3806100206000396000f3fe60806040526004361061003f5760003560e01c806311fee46b1461004457806322ac06a91461004e57806359a5f12d14610076578063d30895e4146100ae575b600080fd5b61004c6100ce565b005b34801561005a57600080fd5b50610063610183565b6040519081526020015b60405180910390f35b34801561008257600080fd5b50600154610096906001600160a01b031681565b6040516001600160a01b03909116815260200161006d565b3480156100ba57600080fd5b50600054610096906001600160a01b031681565b3467016345785d8a00001461012a5760405162461bcd60e51b815260206004820152601860248201527f4e65656420302e3165746820746f20706c61792067616d65000000000000000060448201526064015b60405180910390fd5b4767016345785d8a00000361015a576000805473ffffffffffffffffffffffffffffffffffffffff191633179055565b6001805473ffffffffffffffffffffffffffffffffffffffff191633179055610181610195565b565b60006101906002436102a4565b905090565b600061019f610183565b6000036101b857506000546001600160a01b03166101c6565b506001546001600160a01b03165b600080826001600160a01b031666470de4df82000060405161020b907f3231303030000000000000000000000000000000000000000000000000000000815260050190565b60006040518083038185875af1925050503d8060008114610248576040519150601f19603f3d011682016040523d82523d6000602084013e61024d565b606091505b50915091508161029f5760405162461bcd60e51b815260206004820152601460248201527f4661696c656420746f2073656e642045746865720000000000000000000000006044820152606401610121565b505050565b6000826102c157634e487b7160e01b600052601260045260246000fd5b50069056fea164736f6c634300080d000a";

type GreeterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GreeterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Greeter__factory extends ContractFactory {
  constructor(...args: GreeterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Greeter> {
    return super.deploy(overrides || {}) as Promise<Greeter>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Greeter {
    return super.attach(address) as Greeter;
  }
  override connect(signer: Signer): Greeter__factory {
    return super.connect(signer) as Greeter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GreeterInterface {
    return new utils.Interface(_abi) as GreeterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Greeter {
    return new Contract(address, _abi, signerOrProvider) as Greeter;
  }
}
